# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
     # - image: circleci/node:7.10
       - image: docker:17.05.0-ce-git
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk add --update nodejs nodejs-npm apk yarn
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      - run:
          name: Check docker version
          command: |
            docker version
      # # build and push Docker image
      # - run: |
      #     TAG=0.1.$CIRCLE_BUILD_NUM
      #     docker login iad.ocir.io -u $DOCKER_USER -p $DOCKER_PASS         # (5)
      #     docker build -t cloud_pursuit_west/eca-demo              # (4)
      #     docker push cloud_pursuit_west/eca-demo

