--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:7.10"
    steps: 
      - checkout
      - 
        setup_remote_docker: 
          docker_layer_caching: true
      - 
        run: 
          command: |
              sudo apt-get install -y libssl-dev libffi-dev python-dev build-essential
              bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh) --accept-all-defaults" 
              /home/circleci/bin/oci --help
              sudo cp -f  /home/circleci/bin/oci /usr/bin/oci
              oci --help
              oci -version
          name: "Install OCI CLI"
      - 
        run: 
          command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              sudo chown -R $(whoami) /usr/bin
              mv -f /tmp/docker/* /usr/bin
              docker --version
          name: "Install Docker client"
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - 
        run: "yarn install"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      - 
        run: "yarn test"
      - 
        run: 
          command: |
              docker version
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker build -t nodejscc .
              docker tag nodejscc $DOCKER_USER/nodejscc
              docker login docker.io -u $DOCKER_USER -p $DOCKER_PASS
              docker images
              docker push $DOCKER_USER/nodejscc
          name: "Build Docker Image"
    working_directory: ~/repo
version: 2
